### ISSUE TITLE
Review SecurityHeaaders.io suggestions

### ISSUE THREAD

**Issue by plaintextcity** [grempe/diceware#13]
Another suggestion for improvement, there are more security headers that can be enabled to block external attacks, see site linked below (site by @scott_helme).

https://securityheaders.io/?q=https%3A%2F%2Fwww.rempe.us%2Fdiceware%2F%23diceware&hide=on

Enabled (good):
Strict-Transport-Security 
X-Content-Type-Options 

Review suggestions:
Content-Security-Policy 
X-Frame-Options 
X-XSS-Protection

Handle with caution:
Public-Key-Pins

**Comment by grempe** [comment]
Thanks for the feedback. I've used that site before and I make use of those security enhancements where I can.

In this case, since all of www.rempe.us is served as a static site through github pages (and then through the fast.ly and cloudflare) CDN) I do not have the same level of control over headers as I would if I were self hosting with an HTTP server I fully configure.

You can learn more about my site and its setup here.

https://www.rempe.us/about/

I have a number of strong security measures in place (HSTS, HTTPS, Sub Resource Integrity Hashes, etc). If you feel you need more I would suggest cloning the repo and running it offline.

Thank you
