### ISSUE TITLE
What's going on with the hash benchmark data?

### ISSUE THREAD

**Issue by cottsak** [grempe/diceware#17]
I'm assuming ["350 billion hashes/second"](https://github.com/grempe/diceware/blob/master/index.html#L147) is referring to the `350.8 GH/s` MD4 value on https://gist.github.com/epixoip/a83d38f412b4737e99bbef804a270c40 Am I right?

If that's the case, then I'm confused. [This device](https://gist.github.com/epixoip/63c2ad11baf7bbd57544) claims higher bcrypt speeds than the one [you reference](https://gist.github.com/epixoip/a83d38f412b4737e99bbef804a270c40); but slower MD4 numbers. Is that a glitch or just an artefact of the different hardware and how different hashes perform on said hardware?

**Comment by grempe** [comment]
Well, to be clear, I reference that page not to pick any particular hash and the rate it can be cracked, but merely to demonstrate that there are rigs available to almost anyone that can attempt hundreds of billions of hashes per second.

Many people, when dealing with passwords and the ability of an attacker to guess them, think about humans guessing and I'm trying to impress on them that there are machines capable today of performing brute force attacks at rates that might be unimaginable to regular people who don't know anything about cracking rigs. Also we can use that to try and put into context what a nation state might possibly be capable of.

As far as the data issue you mentioned with those two links you listed I honestly have no idea what's behind that difference.  If I were to guess I might wonder if it could be a memory available difference between the two setups as bcrypt is more memory hard being a key derivation function than MD4 (way obsolete) which is just a simple one-way hash function and isn't memory intensive.

Also, I don't use that 350 GH/sec number in my calculations though and just take a reasonable stab at what currently plausible crack rates for (non-KDF) password hashes exposed in a breach might be (the trillion/sec guesstimate).

Since the data you question is outside of my control though I'll close this issue. :-)

**Comment by cottsak** [comment]
Thanks mate. Very helpful. This wasn't an "issue"; just me trying to understand the intentions more. I particularly like this:

>  I'm trying to impress on them that there are machines capable today of performing brute force attacks at rates that might be unimaginable to regular people who don't know anything about cracking rigs. 

Love what you're doing. We need a better mainstream understanding of these issues. Thanks from all of us.
