### ISSUE TITLE
better wordlists (remove non-words)

### ISSUE THREAD

**Issue by My1** [grempe/diceware#55]
This tool is fun but honestly the entropy is kinda going down when you have to skirt around random junk all day like "zp" or a whole lot of number stuff on the lists or "aa", "aaa" and "aaaa" as well.

on the german wordlist for example I could throw out the first 244 entries and probably some more later and at the end because they make this thing borderline unusable and just plain bad.

if numbers or symbols are needed one could just throw them on extra instead of just making the lists worse than they should be.

sure you didnt create the lists but maybe you or someone reading here can help improving them

**Comment by grempe** [comment]
> This tool is fun but honestly the entropy is kinda going down when you have to skirt around random junk all day like "zp" or a whole lot of number stuff on the lists or "aa", "aaa" and "aaaa" as well.

The value of these words has no bearing on the amount of entropy in the resultant passphrase.

> on the german wordlist for example I could throw out the first 244 entries and probably some more later and at the end because they make this thing borderline unusable and just plain bad.

This German wordlist is sourced from the website of the creator of Diceware.

http://world.std.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline

If you have a better wordlist for German, feel free to provide a pull request with a link to the source of the list.

> if numbers or symbols are needed one could just throw them on extra instead of just making the lists worse than they should be.

Not sure I understand this. Again, the content of the lists has no bearing on the entropy of the generated passphrases.

> sure you didnt create the lists but maybe you or someone reading here can help improving them

Maybe that someone is you? ;-)

Thanks for the feedback, but since this report isn't actionable I'll close it now. Feel free to request re-open.

**Comment by My1** [comment]
> The value of these words has no bearing on the amount of entropy in the resultant passphrase.

it kinda does when you retry passwords until you get one that doesnt have that in.

> Not sure I understand this. Again, the content of the lists has no bearing on the entropy of the generated passphrases.

as said when you hit regenerate password every time one of these "junk words" shows up you are effectively shortening the list length by how many of them exist, and thereby the practical entropy.

> Maybe that someone is you? ;-)

I'd love to but I have no expertise in what words would be a good choice, and thought to open the issue in hope someone reading around does have some idea for a better list

**Comment by DonaldTsang** [comment]
@My1 @grempe I would like to say that a lot of those "junk words" are actually filler, since it might be hard to get unique words to put in the wordlist. also it might be an entropy buffer. BUT if anyone is interested we can pick some words to replace such "junk", just make a pull request.

**Comment by My1** [comment]
I see. I know that at least for English 1password uses a wordlist with around 17k words or so. Which can be easily pulled from their mac app (even without a mac it's not hard) and i often use for digitally creating Diceware style passwords with a much larger list tho.

**Comment by grempe** [comment]
Since we are getting into discussion of what is essentially the suggestion to create new word lists, that contain fewer "filler" words for certain languages I'm going to lock this issue for now. If there is the desire to create and add new word lists a new issue with associated pull request is the path forward. I won't modify the existing word lists pulled from upstream Diceware sources.
